env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
  space-infix-ops: error
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  keyword-spacing:
    - error
  space-before-function-paren:
    - error
  no-console:
    - warn
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - off
    - windows
  quotes:
    - error
    - single
  brace-style:
    - error
    - stroustrup
  semi:
    - error
    - never
  max-len:
    - error
    - 120
    - ignoreComments: true
      ignoreRegExpLiterals: true
  no-trailing-spaces:
    - error
    - ignoreComments: true
  no-prototype-builtins:
    - error
  no-useless-catch:
    - off
  lines-between-class-members:
    - error
    - always
  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
        - var
      next: "*"
    - blankLine: any
      prev:
        - const
        - let
        - var
      next:
        - const
        - let
        - var
    - blankLine: always
      prev: block-like
      next: "*"
    - blankLine: any
      prev: case
      next: "*"